[advisories]
yanked = "deny"
ignore = []

[licenses]
allow = [
  "Unlicense",
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
]


[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
